### ISSUE TITLE
Brushing not compatible with zoom

### ISSUE THREAD

**Issue by joperea** [MSU-CEDAR/cedarmapper#8]
When zooming out, the brush region does not adapt.

**Comment by billspat** [comment]
brushing DOES zoom, but brush area is not full window, and is not apparent to user.   Brush rectangle also rotates with graph.   Moving brush to different group to avoid these transforms, or transforming only graph and not brush, breaks brush (nodes are selected but when brushing their original location)

**Comment by billspat** [comment]
Brush rectangle also rotates with the graph.  The lasso plug-in seems an easy solution to this problem because when drawing a lasso there is not specific orientation, and it doesn't seem unusual to not be able to select something outside of the canvas.  However, the brush/lasso only works on clicks on the canvas, which can shrink but nodes can still be pull outside of the canvas area.  Hance the canvas should be expanded to be larger than the graph to fill visible area, else nodes can never be selected with a lasso (or brush )

**Comment by billspat** [comment]
proof of concept with semantic zoom and lasso brush (not applied to Cedar javascript yet): https://jsfiddle.net/billspat/5da0712q/17/
